@startuml
actor Пользователь
actor Администратор
actor Главный_администратор

participant "Система" as System

== Регистрация ==
Пользователь -> System: Номер телефона, пароль
Пользователь <-- System: Регистрация либо сообщение о невалидных данных
Пользователь <-- System: Выдача базовой роли User

== Авторизация ==
Пользователь -> System: Номер телефона, пароль
Пользователь <-- System: Вход в приложение или сообщение об несоответствии данных

== Назначение роли с запросом от пользователя ==
Пользователь -> System: Запрос о выдаче определённой роли
System -> Администратор: Запрос о выдаче определённой роли
System <-- Администратор: Подтверждение или отклонение запроса о выдаче определённой роли
Пользователь <-- System: Выдача или невыдача определённой роли

== Назначение роли без запроса пользователя ==
Администратор -> System: Выдача определённой роли определённому пользователю
Пользователь <-- System: Выдача роли

== Удаление роли с запросом от пользователя ==
Пользователь -> Администратор: Запрос на удаление роли
Пользователь <-- Администратор: Подтверждение или отклонение запроса на удаление роли

== Удаление роли без запроса пользователя ==

Администратор -> System: Удаление роли определённому пользователю
Пользователь <-- System: Удаление роли

== Создание секции ==

Главный_администратор -> System: Создание секции
System <-- Администратор: Создание секции

== Удаление секции ==

Главный_администратор -> System: Удаление секции
System <-- Администратор: Удаление секции

== Прикрепить пользователя к сеции ==
Администратор -> System: Прикрепить пользователя к секции
System <-- Администратор: Прикрепление пользователя к секции

== Открепить пользователя от секции ==
Администратор -> System: Открепить пользователя от секции
System <-- Администратор: Открепление пользователя от секции

== Назначить тренера ==

Администратор -> System: Назначить тренера
System <-- Администратор: Назначение тренера

== Открепление тренера ==
Администратор -> System: Открепление тренера
System <-- Администратор: Открепление тренера

== Создание событий в календаре ==
Тренер -> System: Создание события в календаре
Тренер <-- System: Создание события в календаре

== Удаление события из календаря ==
Тренер -> System: Удаление события из календаря
Тренер <-- System: Удаление события из календаря

== Учёт посещаемости ==
Тренер -> System: Отметить посещаемость пользователя
Тренер <-- System: Отметка посещаемости пользователя

== Учёт достижений ==
Тренер -> System: Отметить достижения пользователя
Тренер <-- System: Отметка достижений пользователя

== Анализ эффективности ==

Администратор -> System: Анализ эффективности
Администратор <-- System: Анализ эффективности

@enduml